RNG_SEED: 2
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: 'experiment/train_test'
OPTIM:
  BASE_LR: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.00003
  MAX_EPOCH: 250
TRAIN:
  BATCH_SIZE: 32
  CHANNELS: 48
  LAYERS: 14
SEARCH:
  IM_SIZE: 224