RNG_SEED: 2
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: 'experiment/train'
OPTIM:
  BASE_LR: 0.025
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0003
  MAX_EPOCH: 600
TRAIN:
  BATCH_SIZE: 96
  CHANNELS: 36
  LAYERS: 20
SEARCH:
  IM_SIZE: 32
  