SPACE:
  NAME: 'ofa'
# SEARCH:
#   DATASET: 'cifar10'
#   NUM_CLASSES: 10
#   SPLIT: [0.8, 0.2]
#   BATCH_SIZE: 256
#   IM_SIZE: 32
OPTIM:
  STEPS: [48, 96]
  BASE_LR: 0.025
  LR_POLICY: 'cos'
  MAX_EPOCH: 300
TRAIN:
  BATCH_SIZE: 32
SNG:
  NAME: 'RAND'
  WARMUP_RANDOM_SAMPLE: False
  RANDOM_SAMPLE: False
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: 'experiment/rand_ofa_test'
